### ISSUE TITLE
Blog 详情页6处优化

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#101]
![image](https://user-images.githubusercontent.com/16741975/198755692-76cede92-313c-4e45-b43f-42c9d8e84583.png)

另外，

1. 阅读导航建议去掉框（简化），且它仅在电脑访问下出现，手机和平板模式不出现
2. 详情内容段落中的行距（特别是标题）急需优化

**Comment by zhaojing1987** [comment]
已修正
