### ISSUE TITLE
增加一个试用页面

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#115]
## 需求

方便客户快速演示，同时提供产品的购买和反馈通道

1. 主要内容分为三个板块：演示URL和账号密码；几大云市场购买链接；反馈通道（github 标星，加群等）
2. 页面名称：try or demo
3. 原型设计工具：[softr.io](https://studio.softr.io/) （已发送邀请账号）

**Comment by zhaojing1987** [comment]
已完成
