### ISSUE TITLE
site memu not at one line

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#121]
![image](https://github.com/Websoft9/www.websoft9.com/assets/16741975/9452bb1b-a3f6-4a81-b88f-c6fb191a2a89)

![image](https://github.com/Websoft9/www.websoft9.com/assets/16741975/0b9fba78-e8a4-4901-a36f-4638550d965d)

**Comment by chendelin1982** [comment]
感觉 价格 项与其他的脱节

**Comment by qiaofeng1227** [comment]
官网菜单样式的问题，主要还是网络问题导致样式加载慢，可能加载了默认样式导致的，做了修复优化。需要监控是否ok
