### ISSUE TITLE
添加站点流量统计工具

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/www.websoft9.com#126]
添加站点流量统计工具，便于分析网站流量来源和搜索喜好（关键词设置），例如以下工具
- [百度统计](https://tongji.baidu.com/main/homepage/10000015886/homepage/index)
- 自建统计工具 Matomo 等

**Comment by chendelin1982** [comment]
Have enable Cloudflare for analysis
![image](https://github.com/user-attachments/assets/c81d2659-a0ce-42a4-9412-3e51acb1c8ad)
