### ISSUE TITLE
顶部菜单布局优化

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#20]
如果采用全宽，建议参考：阿里云、腾讯云、华为云首页菜单分布
![image](https://user-images.githubusercontent.com/16741975/192235304-35cea533-072d-40df-91b0-86ce48c19dd6.png)

**Comment by zhaojing1987** [comment]
采用新的菜单布局：
`import HeroArea from "@containers/hero/layout-02";`
删除顶部快捷菜单，加入到新版菜单右侧；
搜索框加到“语言”框前面；
主导航菜单向左移动；
修改Logo大小，含顶部、底部菜单中的logo；
