### ISSUE TITLE
视频类 hero 建议改为“图片+弹出播放的方式”

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#21]
![image](https://user-images.githubusercontent.com/16741975/192415346-2073b347-f1d3-4019-b934-2383d885832c.png)
来源：https://www.contentful.com/

**Comment by zhaojing1987** [comment]
采用 react-modal-video 组件：
import ModalVideo from "react-modal-video";
```
<ModalVideo
        channel="custom"  //声明通道为自定义
        url={video_link}      //指定视频地址
        isOpen={isOpen}
        onClose={onClose}
    />
```
