### ISSUE TITLE
solution  详情页 Markdown 内容中的【列表项】没有渲染出效果

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#24]
![image](https://user-images.githubusercontent.com/16741975/192448140-f655f93f-39f9-4c88-98fd-ff240aebf53e.png)

**Comment by zhaojing1987** [comment]
解决方案：
新增当前页面（@containers/cta/layout-06）针对ul标签的样式，用于覆盖全站的ul样式：
```
ul {
        list-style-type:disc;
        list-style-position:inside;
    }
```
