### ISSUE TITLE
中文页面的title当前为英文内容

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#25]
![image](https://user-images.githubusercontent.com/16741975/192448979-5b3771af-c4f6-4e6b-89ac-81a15d68b4f3.png)
需根据语言显示

**Comment by zhaojing1987** [comment]
解决方案：
在contentful-Page表有数据的页面通过Page-title字段来显示页面title；
对于资源详情页，title显示用资源标题；
对于产品详情页，title显示用trademark；
