### ISSUE TITLE
Gallays 展示优化-

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#28]
![image](https://user-images.githubusercontent.com/16741975/192922187-33ba2704-6554-4d10-a3bd-b56ef28a844c.png)

有提示，让用户知道可以滚动阅读

**Comment by zhaojing1987** [comment]
修改 当前Gallays展示组件，采用组件： @containers/elements/flexible-image-slider/full-wide-slider2
效果：
![image](https://user-images.githubusercontent.com/7624828/192985055-8fad90fe-5f16-4e8c-a61f-1c97cf9ff1d9.png)
