### ISSUE TITLE
资质与荣誉 block 下边距

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#29]
![image](https://user-images.githubusercontent.com/16741975/192928512-e66ea0a8-43e1-4d3d-9dbe-7b8eb4ae3424.png)

下边距需优化

**Comment by zhaojing1987** [comment]
更换荣誉与资质显示组件，调整后：
![image](https://user-images.githubusercontent.com/7624828/194481307-77706074-d2bb-4978-8095-05ed26c0fade.png)
