### ISSUE TITLE
已有博客内容转移到Contentful ￥50

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#31]
login: blog.websoft9.com/ghost

**Comment by zhaojing1987** [comment]
目前blog数据存储在：blog.websoft9.com/ghost，希望将所有blog数据迁移到Contentful 
任务：

1. 实现方式一：技术实现，通过ghost和Contentful 的API实现数据的自动迁移
2. 实现方式二：手动实现，手动循环逐条复制迁移
该任务截止时间10月21日 17:00

**Comment by laozhou0731** [comment]
共 81 个 published 文章

**Comment by zhaojing1987** [comment]
数据规范：

1. 数据迁移至Contentful 表 Resource
2. Resource字段解释：
Type：资源类型，引用型 包括：blog、news等，必需，根据ghost中Tags标签区分，Tags为新闻与活动 公益 公告的对应Resource的Type为news，其它暂时为news
Slug：根据Title-English自动生成，必需，但是目前没有集中对资源进行英文翻译，该字段取ghost中“Post settings-Post URL”
Title：标题，必需
FeatureImage：封面图 ，非必需
Content：内容，必需
Author：作者，引用型，必需。默认选：Websoft9
Time：时间，必需，选ghost原发布时间

**Comment by zhaojing1987** [comment]
已完成
