### ISSUE TITLE
资源的子分类增加一行【类目标题+分类】

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#32]
可参考：
![image](https://user-images.githubusercontent.com/16741975/192956994-81b6269e-bd32-46f2-ab14-c5240cbd5b05.png)

**Comment by zhaojing1987** [comment]
1. 修改resource-type模板页，删除顶部Hero
2. 增加“浏览所有+类别”字符
3. 增加根据“解决方案”查询下拉框
4. 效果：
![image](https://user-images.githubusercontent.com/7624828/194745492-3d5fbc0e-8343-488d-ac09-50b2d8914343.png)
