### ISSUE TITLE
关于我们资质和荣誉图片请统一大小规格

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#34]
Tan and Zhao 两人敲定方案，并实施

**Comment by zhaojing1987** [comment]
调整图片显示组件，调整样式：
        width: 380px;
        height: 234px;
        object-fit:cover;
![image](https://user-images.githubusercontent.com/7624828/194479100-8b49ad42-75a9-4916-91a3-020d7609676b.png)
