### ISSUE TITLE
Contact us Block 建议一分为二

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#36]
![image](https://user-images.githubusercontent.com/16741975/192996627-c2ff77cd-7c4b-4f68-9958-6cc113eb78fa.png)

**Comment by chendelin1982** [comment]
contentful 已经拆分：
![image](https://user-images.githubusercontent.com/16741975/192997543-3852b435-ea65-449f-8a97-f7f33b041a00.png)

考虑程序编译问题，目前没有删除【Contact us】中的 Features

**Comment by zhaojing1987** [comment]
新增一个组件显示新增的Block，并调整数据显示顺序，并删除contentful中原有数据
