### ISSUE TITLE
产品菜单下的 features 页面实现方式优化

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#39]
由多个 Block，改成一个 循环 block （从多个feature中获取数据）

**Comment by chendelin1982** [comment]
1. 准备 Feature （已经完成）
2. 准备 Block  （已经完成，名称为：Product Features）
3. 代码修正
4. 删除无用的 Block

**Comment by zhaojing1987** [comment]
1. 已调整代码，修改数据显示方式
2. 已删除无用Block
