### ISSUE TITLE
优化：价格页面，中文显示¥，美元显示 $

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#44]
当前全部都是$，需优化。
建议货币单位由contentful中维护

**Comment by zhaojing1987** [comment]
修改：

1. 在contentful中价格前加单位：人民币加¥，美元加 $ 
2. 前端代码，通过截取价格的第一个字符作为货币符号
3. 前端代码，通过截取价格的第二个字符及以后的字符作为价格数字
