### ISSUE TITLE
优化：顶部右侧菜单自适应问题

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#46]
![image](https://user-images.githubusercontent.com/16741975/194279288-2ba113ee-7178-46d3-a0f1-a16a40c6536e.png)

不应该在主菜单区域之外

![image](https://user-images.githubusercontent.com/16741975/194279356-7e657b3a-eddf-4854-ae16-008ceca8817b.png)

**Comment by zhaojing1987** [comment]
已解决
