### ISSUE TITLE
应用列表页中的分类菜单 宽度加宽

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#53]
![image](https://user-images.githubusercontent.com/16741975/194983379-9c8570ea-46ff-49a4-a9ff-1318dc6d03ac.png)

尽量适应英文的一级菜单

**Comment by zhaojing1987** [comment]
调整分类比例，效果：
![image](https://user-images.githubusercontent.com/7624828/195527714-523a1b25-dd0b-4620-827a-f4200f9cace4.png)
