### ISSUE TITLE
Logo 垂直位置需调整

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#61]
![image](https://user-images.githubusercontent.com/16741975/196066342-f8ce6323-ea98-4d5e-a1fe-646b6e3a78ba.png)

管用的做法是：垂直居中

**Comment by zhaojing1987** [comment]
修改logo样式：采用flex布局
```
    display:flex;
    justify-content: flex-start;
    align-items:center;
    align-content:center;
```
