### ISSUE TITLE
Automatic backup for contentful  - pay ¥100

### ISSUE THREAD

**Issue by zhaojing1987** [Websoft9/www.websoft9.com#68]
## Describe this issue
-  要求：在 github 设定自动任务，利用contentful 工具自动备份数据
-  线索：
     [contentful 数据导入导出工具](https://github.com/Websoft9/www.websoft9.com/tree/main/contentful)
     [Github Action文档](https://docs.github.com/cn/actions)

#### What type of this issue?

- [ ] research report
- [x] coding
- [ ] unique task

#### Need skills and know how

- [x] Contentful
- [ ] React
- [ ] Bootstrap
- [ ] GraphQL
- [ ] CSS
- [x] Github Action
- [x] contentful 数据导入导出工具
- [ ] ...

## Plan and do - Sub Tasks list

- [x] Task1：学会使用 contentful 数据导入导出工具
- [x] Task2：学会使用 github action
- [x] Task3：利用 github action 和 contentful 数据导出工具 实现数据备份

## Check with these people

- [ ] Xu
- [ ] Darren Chen
- [ ] Zhou
- [x] Zhao

## Optimize docs or process

Please fill the docs link below:  

### 使用路径说明:

1. 配置文件：contentful/export-config.json
2. 备份数据：contentful/备份日期/export.json
3. 日志文件：contentful/备份日期/error.json

> 说明：日期格式为：**年-月-日**，例如2022-10-26

### 备份任务结果说明：

1. github action指令运行出错或push文件至仓库出错，给指定人发送邮件通知，无附件
2. contentful导出数据出错，给指定人发送邮件通知，附件为日志文件【**error.json**】
3. 备份任务执行成功（即成功push备份数据至仓库且没有其他出错），给指定人发送邮件通知，附件为备份数据【**export.json**】,此为二次备份

#### 1. step说明：
```
- id: setup
   配置node环境

- id: install
   下载contentful cli 数据导出工具

- id: export
   使用contentful cli 指令导出数据

- id: push
  将导出的数据或者日志push到仓库中

- id: conclusion
  获取以上step的运行情况以及备份的情况，用于下一步编辑邮件内容 

- name: edit the email content out of the export job output
  编写邮件内容
  
- name: Send inform mail
  发送邮件
```
#### 2. on——任务流触发方式
- 手动触发：
```
on: 
   workflow_dispatch
```
- 定时触发：
```
on: 
  schedule:
  - cron: "0 12 * * 5"  
```
参数说明：

![Image](https://user-images.githubusercontent.com/62973206/198202700-6a158802-8b78-41cf-86e8-fdd7975d2c6d.png)

![Image](https://user-images.githubusercontent.com/62973206/198202869-e8c906c7-46df-4671-8ae2-81a0da7ca954.png)

说明：

- 这里的时间为UTC时间，**北京时间=UTC时间+8H**

例如：
- 0 12 * * 5 表示每周星期五的12：00（UTC）执行，对应中国时间的20：00
- 30 1,3 * * 6 表示每周六的1：30和3：30（UTC）执行

#### 3.  step(id:export)包含contentful cli 导出数据指令，参数说明

- --config：指令配置文件路径
- --export-dir：导出数据存储路径（不包含导出文件的名字）
- --error-log-file：出错日志存储路径（包含日志名）
- --mt：contentful的token

> 说明：由于token具有私密性，所以存储在仓库的secrets里面,使用方式：${{secrets.secrets_name}}

#### 4. step中最后一步为发送备份结果邮件
- server_address与server_port对应关系:
| smtp.163.com  |  25   |
| smtp.qq.com    | 465 |

- username与password为发送邮件方的邮箱与smtp服务码

> 说明：两者均存储在secrets中，使用${{ secrets.MAIL_USERNAME }}与${{ secrets.MAIL_USERNAME }}

- to 表示接受邮件方的邮箱
> 也可储存在secrets中

- subject：邮件主题
- body：邮件内容
- attachments：邮件附件

>以上内容均可在前一个step中进行修改

#### 补充：
添加一个环境变量，用于step与step之间传递数据
```
echo "{environment_variable_name}={value}" >> $GITHUB_ENV
```
使用方式：`${{environment_variable_name}}`

**Comment by zl-go** [comment]
## 使用路径说明:

1. 配置文件：contentful/export-config.json
2. 备份数据：contentful/备份日期/export.json
3. 日志文件：contentful/备份日期/error.json

> 说明：日期格式为：**年-月-日**，例如2022-10-26

## 备份任务结果说明：

1. github action指令运行出错或push文件至仓库出错，给指定人发送邮件通知，无附件
2. contentful导出数据出错，给指定人发送邮件通知，附件为日志文件【**error.json**】
3. 备份任务执行成功（即成功push备份数据至仓库且没有其他出错），给指定人发送邮件通知，附件为备份数据【**export.json**】,此为二次备份

## github action代码说明：

### 1. step说明：
```
- id: setup
   配置node环境

- id: install
   下载contentful cli 数据导出工具

- id: export
   使用contentful cli 指令导出数据

- id: push
  将导出的数据或者日志push到仓库中

- id: conclusion
  获取以上step的运行情况以及备份的情况，用于下一步编辑邮件内容 

- name: edit the email content out of the export job output
  编写邮件内容
  
- name: Send inform mail
  发送邮件
```
### 2. on——任务流触发方式
- 手动触发：
```
on: 
   workflow_dispatch
```
- 定时触发：
```
on: 
  schedule:
  - cron: "0 12 * * 5"  
```
参数说明：


![Image](https://user-images.githubusercontent.com/62973206/198202700-6a158802-8b78-41cf-86e8-fdd7975d2c6d.png)


![Image](https://user-images.githubusercontent.com/62973206/198202869-e8c906c7-46df-4671-8ae2-81a0da7ca954.png)

说明：

- 这里的时间为UTC时间，**北京时间=UTC时间+8H**

例如：
- 0 12 * * 5 表示每周星期五的12：00（UTC）执行，对应中国时间的20：00
- 30 1,3 * * 6 表示每周六的1：30和3：30（UTC）执行

### 3.  step(id:export)包含contentful cli 导出数据指令，参数说明

- --config：指令配置文件路径
- --export-dir：导出数据存储路径（不包含导出文件的名字）
- --error-log-file：出错日志存储路径（包含日志名）
- --mt：contentful的token

> 说明：由于token具有私密性，所以存储在仓库的secrets里面,使用方式：${{secrets.secrets_name}}

### 4. step中最后一步为发送备份结果邮件
- server_address与server_port对应关系:
| smtp.163.com  |  25   |
| smtp.qq.com    | 465 |

- username与password为发送邮件方的邮箱与smtp服务码

> 说明：两者均存储在secrets中，使用${{ secrets.MAIL_USERNAME }}与${{ secrets.MAIL_USERNAME }}

- to 表示接受邮件方的邮箱
> 也可储存在secrets中

- subject：邮件主题
- body：邮件内容
- attachments：邮件附件

>以上内容均可在前一个step中进行修改

### 补充：
添加一个环境变量，用于step与step之间传递数据
```
echo "{environment_variable_name}={value}" >> $GITHUB_ENV
```
使用方式：`${{environment_variable_name}}`

**Comment by zhaojing1987** [comment]
已完成
