### ISSUE TITLE
GitHub Action for Website - pay ¥50

### ISSUE THREAD

**Issue by zhaojing1987** [Websoft9/www.websoft9.com#69]
## Describe this issue
      实现官网项目在 GitHub Pages上自动发布

#### What type of this issue?

- [ ] research report
- [x] coding
- [ ] unique task

#### Need skills and know how

- [ ] Contentful
- [ ] React
- [ ] Bootstrap
- [ ] GraphQL
- [ ] CSS
- [x] Github Action
- [ ] ××× API
- [ ] ...

## Plan and do - Sub Tasks list

- [x] Task1：学会使用 GitHub Action
- [x] Task2：学会使用 GitHub Pages
- [x] Task3：自动发布官网

## Check with these people

- [ ] Xu
- [ ] Darren Chen
- [ ] Zhou
- [x] Zhao

## Optimize docs or process

Please fill the docs link below:

**Comment by zhaojing1987** [comment]
文档参考：https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/

**Comment by Tooy1011** [comment]
# pages.yml

**运行效果：对网页代码进行编译并发布到github pages上，同时将编译后修改的public文件夹push到仓库，即对仓库的public文件夹进行更新。**

基于自动生成的发布网站的脚本所做修改如下：

设置触发action的方式为手动触发

```bash
on: 
    workflow_dispatch:
```

使用 permissions 修改授予 GITHUB_TOKEN 的默认权限

```bash
permissions:
    # 设置对仓库内容的权限为写，使得可以将编译修改后的public文件夹更新到仓库当中
    contents: write
    # 设置允许部署到github pages
    pages: write
    id-token: write
```

修改工作目录，设置为发布的网站所在的目标目录。
如下设置根目录为souce文件夹。

```bash
defaults:
    run:
        shell: bash
        working-directory: ./source
```

修改发布的网站的文件所在位置为./source.public

```bash
- name: Upload artifact
    uses: actions/upload-pages-artifact@v1
    with:
        path: ./source/public
```

将编译后修改过的文件push到仓库

```bash
- id: push
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
        commit_message: "update public"
```

**Comment by zhaojing1987** [comment]
已完成
