### ISSUE TITLE
网站英文版本无法跳转 文档英文版本

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/www.websoft9.com#74]
![image](https://user-images.githubusercontent.com/43192516/197475679-caf4591c-55f8-4172-8526-13572e668003.png)

![image](https://user-images.githubusercontent.com/43192516/197475750-16075419-922e-4d28-9024-0d4951134785.png)

**Comment by zhaojing1987** [comment]
为菜单的Link新增多语言，语言切换时根据语言导航
