### ISSUE TITLE
资源详情页顶部优化

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/www.websoft9.com#82]
![image](https://user-images.githubusercontent.com/16741975/197694997-407d1695-864f-44f9-9220-0f286c6e919a.png)

1. Feature 图片比例改成 4:3
2. : 后面空额
3. 作者：去掉作者二字，职位前面+公司名字
4. 时间建议放到【标题】下面，标题上面是【资源类型】
![image](https://user-images.githubusercontent.com/16741975/197699187-aba1e372-8cda-4801-a4f5-0758aa9a70ad.png)

**Comment by zhaojing1987** [comment]
已修订
