### ISSUE TITLE
产品的相关产品格式建议与产品列表一致

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/www.websoft9.com#89]
![image](https://user-images.githubusercontent.com/62225175/197706292-b96a430a-d074-40a3-b40b-594f76842b0e.png)
VS
![image](https://user-images.githubusercontent.com/62225175/197706453-d22d2b37-9b69-41b2-ad9d-adfd91b5ad29.png)

**Comment by zhaojing1987** [comment]
已优化
